### ISSUE TITLE
Only the first space character is replaced with dash in parrot image filename

### ISSUE THREAD

**Issue by Mattias-** [reimertz/countryparrots#2]
https://github.com/reimertz/countryparrots/blob/master/generateParrots.js#L36
https://github.com/reimertz/countryparrots/blob/master/generateIndex.js#L7

`.replace(' ', '-')` will only replace one space. Use `.split(' ').join('-')` to replace all occurrences.

**Comment by reimertz** [comment]
<3

fixed.

**Comment by reimertz** [comment]
fi
